### ISSUE TITLE
Make a REST API spec from FFIG

### ISSUE THREAD

**Issue by petr-tik** [FFIG/www#3]

**Comment by jbcoe** [comment]
I'd mentally flagged the `www` repo as just html and css, a simple web page. Maybe we can add a `rest-api` repo for the server?

**Comment by ajbennieston** [comment]
That was how I saw it too. Just the static landing page, with a link to ffig-explorer, which would have a web interface and a REST service.

**Comment by ajbennieston** [comment]
We now have the rest-api repository for this. Closing this ticket.
